name: suite2p2
channels:
  - conda-forge
dependencies:
  - python>=3.7.6,<3.8
  - pip
  - mkl_fft=1.2.0
  - pyqt
  - mkl
  - tbb
  - numpy
  - numba
  - matplotlib
  - scipy
  - scikit-learn
  - pip:
    - h5py==2.10.0
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb<1.4.0
    - suite2p